"""changed fk:  residence_id to be null for image object

Revision ID: 8c92b640c707
Revises: c83d427c71d7
Create Date: 2024-10-16 23:41:48.517781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c92b640c707'
down_revision = 'c83d427c71d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('residence_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('residence_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
