"""added surface_area to land

Revision ID: f67a4e520438
Revises: 8c92b640c707
Create Date: 2024-10-17 01:03:35.796831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f67a4e520438'
down_revision = '8c92b640c707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('land', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surface_area', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('land', schema=None) as batch_op:
        batch_op.drop_column('surface_area')

    # ### end Alembic commands ###
